services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: on-failure
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: on-failure
    env_file: .env
    depends_on:
      - mariadb
    secrets:
      - db_password
      - credentials
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/Adminer
    container_name: adminer
    image: adminer
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/FTP
    container_name: ftp
    image: ftp
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception

  netdata:
    build: ./requirements/bonus/Netdata
    container_name: netdata
    image: netdata
    restart: on-failure
    ports:
      - "19999:19999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - inception

  redis:
    build: ./requirements/bonus/Redis
    container_name: redis
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - inception
      
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
      - static_website:/var/www/static:ro
    networks:
      - inception

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/khhihi/data/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/khhihi/data/wordpress
  redis_data:
    driver: local
  static_website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/khhihi/data/static_website

networks:
  inception:
    driver: bridge